# Generated by Django 4.1.4 on 2023-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceimages',
            name='tags',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
