# Generated by Django 4.1.4 on 2023-03-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
