# Generated by Django 4.1.4 on 2023-03-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceImages',
        ),
    ]
