# Generated by Django 4.1.4 on 2023-03-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_brick_contradictionlist_ktops_redundantlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcefile',
            old_name='proprocessed',
            new_name='preprocessed',
        ),
    ]
