# Generated by Django 4.1.4 on 2023-03-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_proprocessed_sourcefile_preprocessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='preprocessed',
            field=models.BooleanField(default=False),
        ),
    ]
