# Generated by Django 4.1.4 on 2023-04-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_ktops_contradictionlist_sentence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('groups', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='brick',
            name='stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='brick',
            name='workspace',
            field=models.CharField(default=None, max_length=265),
        ),
        migrations.AlterField(
            model_name='referencelist',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.sourcefile'),
        ),
        migrations.CreateModel(
            name='TermList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('term', models.CharField(max_length=100)),
                ('word_count', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brick')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.sourcefile')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sourcefile')),
            ],
        ),
        migrations.CreateModel(
            name='OutdatedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.BigIntegerField()),
                ('sentence', models.CharField(max_length=100)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sourcefile')),
            ],
        ),
    ]
