# Generated by Django 4.1.4 on 2023-04-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_extractinsert_permissionchangerequest_brick_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
