# Generated by Django 4.1.4 on 2023-04-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sourcefile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcefile',
            name='preprocessed',
        ),
    ]
