# Generated by Django 4.1.4 on 2023-04-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_sourcefile_preprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='preprocessed',
            field=models.BooleanField(default=False),
        ),
    ]
