# Generated by Django 4.1.4 on 2023-04-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_brick_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlist',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brick'),
        ),
    ]
