# Generated by Django 4.1.4 on 2023-04-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_termlist_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencelist',
            name='file',
            field=models.FileField(null=True, upload_to='workfile'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
