# Generated by Django 4.1.4 on 2023-04-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_referencelist_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contradictionlist',
            name='sentence',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ktops',
            name='ktops',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='outdatedlist',
            name='sentence',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='redundantlist',
            name='sentence',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
