# Generated by Django 4.1.4 on 2023-04-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_contradictionlist_sentence_alter_ktops_ktops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlist',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sourcefile'),
        ),
    ]
